# Generated by Django 4.1.8 on 2024-09-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_disabled', models.BooleanField(default=True, null=True)),
                ('width', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sortable', models.BooleanField(default=True, null=True)),
                ('is_filterable', models.BooleanField(default=True, null=True)),
                ('filter_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_selected', models.BooleanField(default=True, null=True)),
                ('module_id', models.PositiveIntegerField(null=True)),
                ('user_id', models.PositiveIntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
