# Generated by Django 4.1.8 on 2024-09-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Configuration",
            new_name="ColumnConfiguration",
        ),
        migrations.AlterModelTable(
            name="columnconfiguration",
            table="COLUMN_CONFIGURATION",
        ),
    ]
