# Generated by Django 4.1.8 on 2024-09-03 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenModule',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('expiry_days', models.PositiveIntegerField()),
                ('expiry_time', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('APP_TOKEN', 'APP_TOKEN'), ('LOGIN_TOKEN', 'LOGIN_TOKEN')], db_column='TOKEN_TYPE', default='APP_TOKEN', max_length=255)),
                ('primary_token', models.CharField(blank=True, max_length=120, null=True)),
                ('secondary_token', models.CharField(blank=True, max_length=120, null=True)),
                ('user_id', models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='token_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TOKEN_MANAGEMENT',
                'ordering': ['-created_on'],
            },
        ),
    ]
