# Generated by Django 4.1.8 on 2024-09-03 05:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('response_time', models.TimeField()),
                ('resolution_time', models.TimeField()),
                ('is_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_department', to='master_data_management.department')),
            ],
            options={
                'db_table': 'SLA',
                'ordering': ['created_on'],
            },
        ),
    ]
