# Generated by Django 5.0.6 on 2024-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLA",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("department", models.CharField(max_length=200)),
                ("ticket_type", models.CharField(max_length=200)),
                ("priority", models.CharField(max_length=50)),
                ("response_time", models.DurationField()),
                ("resolution_time", models.DurationField()),
                ("is_delete", models.BooleanField(default=False)),
                ("created_by", models.IntegerField(null=True)),
                ("updated_by", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "SLA",
                "ordering": ["created_at"],
            },
        ),
    ]
