# Generated by Django 5.0.6 on 2024-07-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_management", "0003_projectmanagement_category_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_code",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_type",
            field=models.CharField(max_length=150),
        ),
    ]
