# Generated by Django 5.0.6 on 2024-07-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_management", "0005_tickettype_alter_department_department_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettype",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
