# Generated by Django 5.0.6 on 2024-07-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_management", "0006_tickettype_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickettype",
            name="is_deleted",
        ),
    ]
