# Generated by Django 5.0.6 on 2024-07-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_management", "0011_ticketbehalf_userdepartment"),
        ("ticket_management", "0012_alter_department_department_type"),
    ]

    operations = []
