# Generated by Django 5.0.6 on 2024-08-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_management", "0015_alter_status_status_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="status_code",
            field=models.IntegerField(
                choices=[
                    (5, "VENDOR CREATION INITIATED"),
                    (10, "VENDOR UPDATE INITIATED"),
                    (15, "VALIDATION IN PROGRESS"),
                    (20, "SANCTION CHECK REVIEW"),
                    (25, "SANCTION CHECK SUCCESS"),
                    (30, "PENDING SANCTION CHECK"),
                    (35, "VENDOR REJECTED"),
                    (40, "VENDOR CREATED IN D365"),
                    (45, "FINANCE VP APPROVAL"),
                    (50, "PENDING F-VP APPROVAL"),
                    (55, "PROCUREMENT VP APPROVAL"),
                    (60, "PENDING P-VP APPROVAL"),
                    (65, "LBU APPROVAL"),
                    (70, "LBU APPROVED"),
                    (75, "MDM TEAM APPROVAL"),
                    (80, "PENDING AT MDM TEAM"),
                    (85, "PENDING REQUESTER"),
                    (90, "MANUAL UPDATE"),
                    (95, "PENDING LOB SYSTEM UPDATE"),
                ],
                default=5,
            ),
        ),
    ]
