# Generated by Django 5.0.6 on 2024-08-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_management", "0016_alter_status_status_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hello",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
