# Generated by Django 5.0.6 on 2024-08-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_management", "0017_hello"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hello",
        ),
    ]
