# Generated by Django 5.0.6 on 2024-08-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_management", "0018_delete_hello"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SLA",
        ),
    ]
