# Generated by Django 5.0.6 on 2024-08-06 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_management", "0019_delete_sla"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("response_time", models.DurationField()),
                ("resolution_time", models.DurationField()),
                ("is_delete", models.BooleanField(default=False)),
                ("created_by", models.IntegerField(null=True)),
                ("updated_by", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_department",
                        to="ticket_management.department",
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_priority",
                        to="ticket_management.priority",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_ticket_type",
                        to="ticket_management.tickettype",
                    ),
                ),
            ],
            options={
                "db_table": "SLA",
                "ordering": ["created_at"],
            },
        ),
    ]
