# Generated by Django 5.0.6 on 2024-08-20 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_name", models.CharField(max_length=255)),
                ("email_history_days", models.IntegerField()),
                ("activity_history_days", models.IntegerField()),
                ("client_start_no", models.CharField(max_length=100)),
                ("project_start_no", models.CharField(max_length=100)),
                ("ticket_start_no", models.CharField(max_length=100)),
                ("ticket_auto_close_days", models.IntegerField()),
                ("auto_notification_hours", models.IntegerField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "APP_CONFIGURATION",
            },
        ),
        migrations.CreateModel(
            name="ClientPrivilege",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("privilege", models.PositiveIntegerField()),
                ("client", models.CharField(max_length=100)),
                ("created_by", models.CharField(max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(null=True)),
                ("updated_by", models.PositiveIntegerField(null=True)),
            ],
            options={
                "db_table": "CLIENT_PRIVILEGE",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="MasterModule",
            fields=[
                (
                    "module_id",
                    models.PositiveIntegerField(
                        choices=[
                            (10, "file_type_management"),
                            (20, "client_management"),
                            (30, "vendor_management"),
                            (40, "business_unit_management"),
                            (50, "application_management"),
                            (60, "account_type_management"),
                            (70, "d365fo_setup_management"),
                            (80, "supplier_management"),
                            (90, "carrier_consolidation_management"),
                            (100, "company_management"),
                            (110, "cpp_sanction_assessment_management"),
                            (120, "country_management"),
                            (130, "user_management"),
                            (140, "roles_management"),
                            (150, "currency_management"),
                            (160, "category_management"),
                            (170, "country_management"),
                            (180, "department_management"),
                            (190, "user_department_management"),
                            (200, "status_management"),
                            (220, "ticket_management"),
                            (230, "sla_management"),
                            (240, "customer_management"),
                            (250, "priority_management"),
                        ],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MasterPrivilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "namespace",
                    models.CharField(max_length=64, verbose_name="Namespace"),
                ),
                (
                    "privilege_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Privilege"
                    ),
                ),
                (
                    "privilege_desc",
                    models.CharField(
                        max_length=1000, verbose_name="Privilege Description"
                    ),
                ),
                (
                    "module_id",
                    models.CharField(
                        max_length=1000, verbose_name="Privilege Description"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "PRIVILEGE",
                "ordering": ("privilege_name",),
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role_name", models.CharField(max_length=50, unique=True)),
                (
                    "role_description",
                    models.CharField(
                        blank=True, db_column="role_desc", max_length=1000, null=True
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=1000, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=100)),
                ("updated_by", models.PositiveIntegerField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_on", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "ROLE",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_by", models.CharField(max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "privilege",
                    models.ForeignKey(
                        db_column="privilege_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permission",
                        to="acl.masterprivilege",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permission_role",
                        to="acl.role",
                    ),
                ),
            ],
            options={
                "db_table": "ROLE_PERMISSIONS",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_by", models.CharField(max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_role_role",
                        to="acl.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "USER_ROLE",
                "ordering": ["-created_on"],
            },
        ),
    ]
