# Generated by Django 4.1.8 on 2024-09-04 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("acl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mastermodule",
            name="created_by",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mastermodule",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mastermodule",
            name="modified_by",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mastermodule",
            name="modified_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mastermodule",
            name="module_id",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "FILE_TYPE"),
                    (20, "CLIENT_PERMISSION"),
                    (30, "VENDOR"),
                    (40, "BUSINESS_UNIT"),
                    (50, "USER"),
                    (120, "USER_ROLE"),
                    (140, "ROLE_PRIVILEGES"),
                    (160, "DEPARTMENT_CATEGORY"),
                    (170, "PROJECT"),
                    (220, "DEPARTMENTS"),
                    (230, "SLA"),
                    (240, "CUSTOMER"),
                    (250, "PRIORITY"),
                    (260, "CURRENCY"),
                    (270, "EMAIL_TEMPLATE"),
                    (280, "STATUS"),
                    (290, "TICKET"),
                    (300, "COUNTRY"),
                    (310, "LINE_OF_BUSINESS"),
                    (320, "LEGAL_ENTITY"),
                    (320, "ACTIVITY_LOG"),
                ],
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterModelTable(
            name="mastermodule",
            table="MASTER_MODULE",
        ),
    ]
