# Generated by Django 5.0.6 on 2024-08-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acl", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appconfiguration",
            options={},
        ),
        migrations.RemoveField(
            model_name="appconfiguration",
            name="application",
        ),
        migrations.RemoveField(
            model_name="appconfiguration",
            name="description",
        ),
        migrations.RemoveField(
            model_name="appconfiguration",
            name="group",
        ),
        migrations.RemoveField(
            model_name="appconfiguration",
            name="key",
        ),
        migrations.RemoveField(
            model_name="appconfiguration",
            name="value",
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="activity_history_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="application_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="auto_notification_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="client_start_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="email_history_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="project_start_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="ticket_auto_close_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="ticket_start_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
