# Generated by Django 4.1.8 on 2024-09-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodule',
            name='module_id',
            field=models.PositiveIntegerField(choices=[(10, 'file_type_management'), (20, 'client_management'), (30, 'vendor_management'), (40, 'business_unit_management'), (50, 'application_management'), (60, 'account_type_management'), (70, 'd365fo_setup_management'), (80, 'supplier_management'), (90, 'carrier_consolidation_management'), (100, 'company_management'), (110, 'cpp_sanction_assessment_management'), (120, 'country_management'), (130, 'user_management'), (140, 'roles_management'), (150, 'currency_management'), (160, 'category_management'), (170, 'country_management'), (180, 'department_management'), (190, 'user_department_management'), (200, 'status_management'), (220, 'ticket_management'), (230, 'sla_management'), (240, 'customer_management'), (250, 'priority_management'), (320, 'Activity_log')], primary_key=True, serialize=False),
        ),
    ]
