# Generated by Django 5.0.6 on 2024-08-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acl", "0002_alter_rolepermission_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="created_by",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
