# Generated by Django 4.1.8 on 2024-09-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acl", "0002_alter_mastermodule_module_id"),
        ("acl", "0002_mastermodule_created_by_mastermodule_created_on_and_more"),
    ]

    operations = []
