# Generated by Django 4.1.8 on 2024-09-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acl", "0003_merge_20240905_1212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mastermodule",
            name="module_id",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "FILE_TYPE"),
                    (20, "CLIENT_PERMISSION"),
                    (30, "VENDOR"),
                    (40, "BUSINESS_UNIT"),
                    (50, "USER"),
                    (120, "USER_ROLE"),
                    (140, "ROLE_PRIVILEGES"),
                    (160, "DEPARTMENT_CATEGORY"),
                    (170, "PROJECT"),
                    (220, "DEPARTMENTS"),
                    (230, "SLA"),
                    (240, "CUSTOMER"),
                    (250, "PRIORITY"),
                    (260, "CURRENCY"),
                    (270, "EMAIL_TEMPLATE"),
                    (280, "STATUS"),
                    (290, "TICKET"),
                    (300, "COUNTRY"),
                    (310, "LINE_OF_BUSINESS"),
                    (320, "LEGAL_ENTITY"),
                    (330, "ACTIVITY_LOG"),
                ],
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
