# Generated by Django 5.0.6 on 2024-08-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acl", "0003_alter_appconfiguration_client_start_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appconfiguration",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
