# Generated by Django 5.0.6 on 2024-08-20 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acl", "0007_rolepermission_updated_by_rolepermission_updated_on"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_update_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
