# Generated by Django 4.1.8 on 2024-09-03 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('column_name', models.CharField(max_length=255)),
                ('before_input', models.TextField(blank=True, null=True)),
                ('after_input', models.TextField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create')], max_length=20)),
                ('action_by', models.CharField(blank=True, max_length=255, null=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('table_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_url', models.URLField()),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ACTIVITY_LOG',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CATEGORY',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255, unique=True)),
                ('country_code', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('created_by', models.PositiveIntegerField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'COUNTRY',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100, unique=True)),
                ('currency_code', models.CharField(max_length=10, unique=True)),
                ('created_by', models.PositiveIntegerField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'CURRENCY',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=150)),
                ('department_code', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'DEPARTMENTS',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=255)),
                ('email_to', models.CharField(max_length=255)),
                ('cc', models.TextField(blank=True, null=True)),
                ('bcc', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('signature', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EMAIL_TEMPLATE',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(null=True)),
                ('legal_entity_id', models.CharField(max_length=50, unique=True)),
                ('entity_name', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('ap_contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('business_unit', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('company_number', models.CharField(max_length=50)),
                ('destination_hold', models.CharField(blank=True, max_length=50, null=True)),
                ('ean_number', models.CharField(blank=True, max_length=50, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('overrule_document_group', models.BooleanField(default=False)),
                ('review_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'LEGAL_ENTITY',
            },
        ),
        migrations.CreateModel(
            name='LineOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'LINE_OF_BUSINESS',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('status_code', models.IntegerField(choices=[(5, 'VENDOR CREATION INITIATED'), (10, 'VENDOR UPDATE INITIATED'), (15, 'VALIDATION IN PROGRESS'), (20, 'SANCTION CHECK REVIEW'), (25, 'SANCTION CHECK SUCCESS'), (30, 'PENDING SANCTION CHECK'), (35, 'VENDOR REJECTED'), (40, 'VENDOR CREATED IN D365'), (45, 'FINANCE VP APPROVAL'), (50, 'PENDING F-VP APPROVAL'), (55, 'PROCUREMENT VP APPROVAL'), (60, 'PENDING P-VP APPROVAL'), (65, 'LBU APPROVAL'), (70, 'LBU APPROVED'), (75, 'MDM TEAM APPROVAL'), (80, 'PENDING AT MDM TEAM'), (85, 'PENDING REQUESTER'), (90, 'MANUAL UPDATE'), (95, 'PENDING LOB SYSTEM UPDATE')], default=5)),
                ('color_name', models.CharField(blank=True, max_length=200, null=True)),
                ('color_code', models.CharField(blank=True, max_length=150, null=True)),
                ('highlight', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'STATUS',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='StatusField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'STATUS_FIELDS',
            },
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'USER_DEPARTMENT',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('status_id', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'USER_STATUS',
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='userstatus',
            constraint=models.UniqueConstraint(fields=('user_id', 'status_id'), name='unique_user_status'),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_department_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_department_department', to='master_data_management.department'),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_department_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_department_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statusfield',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_field_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statusfield',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_field_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data_management.country'),
        ),
        migrations.AddField(
            model_name='emailtemplatetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_template_type_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplatetype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_template_type_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_template_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_template_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_template', to='master_data_management.emailtemplatetype'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userdepartment',
            unique_together={('department', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='statusfield',
            unique_together={('status_code', 'field_name')},
        ),
    ]
