# Generated by Django 5.0.6 on 2024-08-20 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("IBAN", "IBAN"), ("Domestic", "Domestic")],
                        max_length=10,
                    ),
                ),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ACCOUNT_TYPE",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("code", models.CharField(blank=True, max_length=25, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.PositiveIntegerField()),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.PositiveIntegerField(null=True)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "APPLICATION",
                "ordering": ["created_on"],
            },
        ),
        migrations.CreateModel(
            name="BusinessUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.CharField(max_length=255, null=True)),
                ("code", models.CharField(max_length=25)),
                ("name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("contact_number", models.CharField(max_length=15)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.PositiveIntegerField()),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.PositiveIntegerField(null=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "BUSINESS_UNIT",
                "ordering": ["created_on"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=25)),
                ("name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("contact_number", models.CharField(max_length=15)),
                ("is_delete", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.PositiveIntegerField()),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.PositiveIntegerField(null=True)),
            ],
            options={
                "db_table": "CLIENT",
                "ordering": ["created_on"],
            },
        ),
        migrations.CreateModel(
            name="CompanyInfoForValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orbis_supplier", models.CharField(max_length=255)),
                ("orbis_bvd", models.CharField(max_length=255)),
                ("vat_supplier", models.CharField(max_length=255)),
                ("vat_validity", models.CharField(max_length=255)),
                ("vat_validity_date", models.DateField()),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "COMPANY_INFO_FOR_VALIDATION",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=255, unique=True)),
                ("country_code", models.CharField(max_length=50)),
                ("description", models.TextField(null=True)),
                ("created_by", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_by", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "COUNTRY",
            },
        ),
        migrations.CreateModel(
            name="CPPSanctionAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cfra_score", models.CharField(max_length=255)),
                ("cfra_portfolio_id", models.CharField(max_length=255)),
                ("cfra_score_card", models.CharField(max_length=255)),
                ("cfra_assessment", models.CharField(max_length=255)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "CPP_SANCTION_ASSESSMENT",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_name", models.CharField(max_length=100, unique=True)),
                ("currency_code", models.CharField(max_length=10, unique=True)),
                ("created_by", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_by", models.PositiveIntegerField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "CURRENCY",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=25)),
                ("name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "retention_period",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "disposal_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ARCHIVE", "ARCHIVE"),
                            ("DELETE", "DELETE"),
                            ("REVIEW", "REVIEW"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "disposal_notification_period",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_delete", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.PositiveIntegerField()),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.PositiveIntegerField(null=True)),
            ],
            options={
                "db_table": "CUSTOMER",
                "ordering": ["created_on"],
            },
        ),
        migrations.CreateModel(
            name="D365FOSetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sales_tax_group", models.CharField(max_length=255)),
                ("vendor_group", models.CharField(max_length=255)),
                ("payment_method", models.CharField(max_length=255)),
                ("business_unit", models.CharField(max_length=255)),
                ("inter_company", models.BooleanField(default=False)),
                ("vendor_hold", models.BooleanField(default=False)),
                ("source_system", models.CharField(max_length=255)),
                ("source_system_supplier_reference", models.CharField(max_length=255)),
                ("d365fo_id", models.CharField(max_length=255)),
                ("fs_ticket_number", models.CharField(max_length=255)),
                ("allow_false_duplicates", models.BooleanField(default=False)),
                ("additional_comments", models.TextField(blank=True, null=True)),
                ("created_by", models.PositiveIntegerField()),
                ("updated_by", models.PositiveIntegerField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "D365FO_SETUP",
            },
        ),
        migrations.CreateModel(
            name="FileType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("file_type", models.CharField(max_length=255)),
                ("file_extension", models.CharField(max_length=25)),
                ("max_file_size", models.PositiveIntegerField()),
                (
                    "file_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.PositiveIntegerField()),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.PositiveIntegerField(null=True)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "FILE_TYPE",
                "ordering": ["created_on"],
            },
        ),
        migrations.CreateModel(
            name="SupplierContactDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_person", models.CharField(max_length=255)),
                ("main_phone_number", models.CharField(max_length=20)),
                ("main_email_id", models.EmailField(max_length=254)),
                (
                    "finance_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "finance_email_id",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "remittance_email_id",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "email_for_receiving_po",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "email_id_for_quote",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("created_by", models.PositiveIntegerField()),
                ("updated_by", models.PositiveIntegerField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "SUPPLIER_CONTACT_DETAILS",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.IntegerField(default=False)),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "retention_period",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "disposal_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ARCHIVE", "ARCHIVE"),
                            ("DELETE", "DELETE"),
                            ("REVIEW", "REVIEW"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "disposal_notification_period",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_delete", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.PositiveIntegerField()),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.PositiveIntegerField(null=True)),
            ],
            options={
                "db_table": "VENDOR",
                "ordering": ["created_on"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "CATEGORY",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=150)),
                ("department_code", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DEPARTMENTS",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "status_code",
                    models.IntegerField(
                        choices=[
                            (5, "VENDOR CREATION INITIATED"),
                            (10, "VENDOR UPDATE INITIATED"),
                            (15, "VALIDATION IN PROGRESS"),
                            (20, "SANCTION CHECK REVIEW"),
                            (25, "SANCTION CHECK SUCCESS"),
                            (30, "PENDING SANCTION CHECK"),
                            (35, "VENDOR REJECTED"),
                            (40, "VENDOR CREATED IN D365"),
                            (45, "FINANCE VP APPROVAL"),
                            (50, "PENDING F-VP APPROVAL"),
                            (55, "PROCUREMENT VP APPROVAL"),
                            (60, "PENDING P-VP APPROVAL"),
                            (65, "LBU APPROVAL"),
                            (70, "LBU APPROVED"),
                            (75, "MDM TEAM APPROVAL"),
                            (80, "PENDING AT MDM TEAM"),
                            (85, "PENDING REQUESTER"),
                            (90, "MANUAL UPDATE"),
                            (95, "PENDING LOB SYSTEM UPDATE"),
                        ],
                        default=5,
                    ),
                ),
                ("color_code", models.CharField(max_length=150)),
                ("highlight", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "STATUS",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_code", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("agent_number", models.CharField(max_length=255)),
                ("supplier_type", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=255)),
                ("terms_of_payment", models.CharField(max_length=255)),
                ("supplier_name", models.CharField(max_length=255)),
                ("siret_number", models.CharField(max_length=255)),
                ("vat_country_code", models.CharField(max_length=255)),
                ("orbis_id", models.CharField(max_length=255)),
                ("orbis_id_found", models.BooleanField(default=False)),
                ("address_line", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=20)),
                ("town", models.CharField(max_length=255)),
                ("country_code", models.CharField(max_length=10)),
                ("swift_number", models.CharField(max_length=255)),
                ("is_prime_revenue", models.BooleanField(default=False)),
                ("created_by", models.PositiveIntegerField()),
                ("updated_by", models.PositiveIntegerField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "account_type",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_details_account_type",
                        to="master_data_management.accounttype",
                    ),
                ),
                (
                    "company_info_for_validation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_details_company",
                        to="master_data_management.companyinfoforvalidation",
                    ),
                ),
                (
                    "cpp_sanction_assessment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_details_sanction",
                        to="master_data_management.cppsanctionassessment",
                    ),
                ),
                (
                    "d365fo_setup",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_details_d365fo",
                        to="master_data_management.d365fosetup",
                    ),
                ),
                (
                    "supplier_contact_details",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_details_supplier",
                        to="master_data_management.suppliercontactdetails",
                    ),
                ),
            ],
            options={
                "db_table": "VENDOR_DETAILS",
            },
        ),
        migrations.CreateModel(
            name="UserDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_department_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_department_department",
                        to="master_data_management.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_department_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_department_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "USER_DEPARTMENT",
                "ordering": ["-created_on"],
                "unique_together": {("department", "user")},
            },
        ),
    ]
