# Generated by Django 4.1.8 on 2024-09-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.PositiveIntegerField(null=True)),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                ("modified_by", models.PositiveIntegerField(null=True)),
                ("vat_number", models.CharField(max_length=50, unique=True)),
                ("dfds_entity_code", models.IntegerField()),
                ("currency", models.IntegerField()),
                ("supplier_source_system", models.IntegerField()),
                ("supplier_type", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "VENDOR",
            },
        ),
    ]
