# Generated by Django 5.0.6 on 2024-08-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="color_name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
