# Generated by Django 4.1.8 on 2024-09-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalentity',
            options={'ordering': ['legal_entity_name'], 'verbose_name': 'Legal Entity', 'verbose_name_plural': 'Legal Entities'},
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='ap_contact_email',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='company_number',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='destination_hold',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='ean_number',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='entity_name',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='overrule_document_group',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='review_flag',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='legalentity',
            name='address_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address City'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='address_country_region_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Address Country Region ID'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='address_country_region_iso_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Address Country Region ISO Code'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='address_description',
            field=models.TextField(blank=True, null=True, verbose_name='Address Description'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Street'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Address ZIP Code'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='bank_account_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account ID'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='currency_code',
            field=models.CharField(default='GBP', max_length=10, verbose_name='Currency Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalentity',
            name='legal_entity_name',
            field=models.CharField(default='LEGAL_ENTITY_NAME', max_length=255, verbose_name='Legal Entity Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalentity',
            name='on_hold_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='On Hold Status'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='sales_tax_group_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sales Tax Group Code'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='vend_source_system',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vendor Source System'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='vend_source_system_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vendor Source System ID'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='vendor_account_number',
            field=models.CharField(default=1, max_length=50, verbose_name='Vendor Account Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalentity',
            name='vendor_group_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vendor Group ID'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='vendor_hold_release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vendor Hold Release Date'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='vendor_organization_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendor Organization Name'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='vendor_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vendor Type'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='legal_entity_id',
            field=models.CharField(max_length=50, verbose_name='Legal Entity ID'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Number'),
        ),
    ]
