# Generated by Django 5.0.6 on 2024-08-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0002_status_color_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="color_code",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="color_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
