# Generated by Django 4.1.8 on 2024-09-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0002_alter_legalentity_options_and_more"),
        ("master_data_management", "0002_vendor"),
    ]

    operations = []
