# Generated by Django 5.0.6 on 2024-08-02 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0003_remove_accounttype_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttype",
            name="vendor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_types",
                to="master_data_management.vendordetails",
            ),
        ),
    ]
