# Generated by Django 5.0.6 on 2024-08-20 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "master_data_management",
            "0003_alter_status_color_code_alter_status_color_name",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("WELCOME", "Welcome Email"),
                            ("RESET_PASSWORD", "Reset Password"),
                            ("TICKET_UPDATE", "Ticket Update"),
                            ("STATUS_UPDATE", "Status Update"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("email_to", models.EmailField(max_length=255)),
                ("cc", models.TextField(blank=True, null=True)),
                ("bcc", models.TextField(blank=True, null=True)),
                ("message", models.TextField()),
                ("signature", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_template_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_template_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "EMAIL_TEMPLATE",
            },
        ),
    ]
