# Generated by Django 4.1.8 on 2024-09-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0003_merge_20240905_1213"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("type", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
    ]
