# Generated by Django 5.0.6 on 2024-08-02 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0004_alter_accounttype_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounttype",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="companyinfoforvalidation",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="cppsanctionassessment",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="d365fosetup",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="suppliercontactdetails",
            name="vendor",
        ),
        migrations.AddField(
            model_name="vendordetails",
            name="account_type",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_details_account_type",
                to="master_data_management.accounttype",
            ),
        ),
        migrations.AddField(
            model_name="vendordetails",
            name="company_info_for_validation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_details_company",
                to="master_data_management.companyinfoforvalidation",
            ),
        ),
        migrations.AddField(
            model_name="vendordetails",
            name="cpp_sanction_assessment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_details_sanction",
                to="master_data_management.cppsanctionassessment",
            ),
        ),
        migrations.AddField(
            model_name="vendordetails",
            name="d365fo_setup",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_details_d365fo",
                to="master_data_management.d365fosetup",
            ),
        ),
        migrations.AddField(
            model_name="vendordetails",
            name="supplier_contact_details",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_details_supplier",
                to="master_data_management.suppliercontactdetails",
            ),
        ),
        migrations.AlterField(
            model_name="vendordetails",
            name="updated_by",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
