# Generated by Django 5.0.6 on 2024-08-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0004_emailtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="email_to",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("ACCOUNT_ACTIVE", "Account Activ"),
                    ("WELCOME", "Welcome Email"),
                    ("RESET_PASSWORD", "Reset Password"),
                    ("TICKET_UPDATE", "Ticket Update"),
                    ("STATUS_UPDATE", "Status Update"),
                ],
                max_length=50,
            ),
        ),
    ]
