# Generated by Django 5.0.6 on 2024-08-07 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0005_remove_accounttype_vendor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="d365fosetup",
            name="created_by",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="d365fosetup",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="d365fosetup",
            name="updated_by",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="d365fosetup",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
