# Generated by Django 5.0.6 on 2024-08-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0005_alter_emailtemplate_email_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("ACCOUNT_ACTIVE", "Account Activ"),
                    ("WELCOME", "Welcome Email"),
                    ("RESET_PASSWORD", "Reset Password"),
                    ("TICKET_UPDATE", "Ticket Update"),
                    ("STATUS_UPDATE", "Status Update"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
