# Generated by Django 4.1.8 on 2024-08-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0007_userstatus"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userstatus",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="userstatus",
            name="created_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userstatus",
            name="modified_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userstatus",
            name="status",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="userstatus",
            name="user",
            field=models.IntegerField(),
        ),
    ]
