# Generated by Django 4.1.8 on 2024-08-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0008_alter_userstatus_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userstatus",
            constraint=models.UniqueConstraint(
                fields=("user", "status"), name="unique_user_status"
            ),
        ),
    ]
