# Generated by Django 4.1.8 on 2024-08-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0010_statusfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statusfield",
            name="status_code",
            field=models.IntegerField(),
        ),
    ]
