# Generated by Django 4.1.8 on 2024-08-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0012_activitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
