# Generated by Django 4.1.8 on 2024-08-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0013_alter_activitylog_action_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="module_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
