# Generated by Django 4.1.8 on 2024-08-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0014_alter_activitylog_module_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("CREATE", "Create"),
                ],
                max_length=20,
            ),
        ),
    ]
