# Generated by Django 4.1.8 on 2024-08-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "master_data_management",
            "0016_emailtemplatetype_alter_emailtemplate_template_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_template",
                to="master_data_management.emailtemplatetype",
            ),
        ),
    ]
