# Generated by Django 4.1.8 on 2024-08-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0017_alter_emailtemplate_template_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplatetype",
            name="template_type",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
