# Generated by Django 4.1.8 on 2024-08-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0018_alter_emailtemplatetype_template_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailtemplatetype",
            old_name="template_type",
            new_name="template_name",
        ),
    ]
