# Generated by Django 4.1.8 on 2024-08-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "master_data_management",
            "0019_rename_template_type_emailtemplatetype_template_name",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LineOfBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
            ],
        ),
    ]
