# Generated by Django 4.1.8 on 2024-08-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data_management", "0020_lineofbusiness"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="lineofbusiness",
            table="LINE_OF_BUSINESS",
        ),
    ]
